bas-amop/PolarRoute

- tests/regression_tests/test_regression.py
Fixing a issue with the regression tests when comparing NaN values. 
Previously when comparing two attributes of a cellbox in `compare_cellbox_values()`, if either of the attributes where NaN the comparison was skipped without reporting an error. Now if either of the attributes are NaN, it only skips without reporting an error if the other attribute is also NaN.
The full regression test suite has been run and has passed for this pull request:
A full log of the regression tests outputs is available: 
[pytest_dump.txt](https://github.com/antarctica/PolarRoute/files/10676147/pytest_dump.txt)
> Reg test fix

- docs/source/sections/Dataloaders/overview.rst
- docs/source/sections/Dataloaders/scalar/index.rst
- docs/source/sections/Dataloaders/vector/index.rst
- polar_route/dataloaders/factory.py
- polar_route/dataloaders/scalar/abstractScalar.py
- polar_route/dataloaders/scalar/amsr.py
- polar_route/dataloaders/scalar/balticSeaIce.py
- polar_route/dataloaders/scalar/bsoseDepth.py
- polar_route/dataloaders/scalar/bsoseSeaIce.py
- polar_route/dataloaders/scalar/density.py
- polar_route/dataloaders/scalar/gebco.py
- polar_route/dataloaders/scalar/icenet.py
- polar_route/dataloaders/scalar/modis.py
- polar_route/dataloaders/scalar/scalarCSV.py
- polar_route/dataloaders/scalar/scalarGRF.py
- polar_route/dataloaders/scalar/shape.py
- polar_route/dataloaders/scalar/thickness.py
- polar_route/dataloaders/vector/abstractVector.py
- polar_route/dataloaders/vector/balticCurrent.py
- polar_route/dataloaders/vector/era5Wind.py
- polar_route/dataloaders/vector/northSeaCurrent.py
- polar_route/dataloaders/vector/oras5Current.py
- polar_route/dataloaders/vector/sose.py
- polar_route/dataloaders/vector/vectorCSV.py
- polar_route/dataloaders/vector/vectorGRF.py
- requirements.txt
- tests/regression_tests/example_meshes/Enviromental_Meshes/create_mesh.output2013_4_80.json
- tests/regression_tests/example_meshes/Enviromental_Meshes/create_mesh.output2016_6_80.json
- tests/regression_tests/example_meshes/Vessel_Performance_Meshes/add_vehicle.output2013_4_80.json
- tests/regression_tests/example_meshes/Vessel_Performance_Meshes/add_vehicle.output2017_6_80.json
Updated the factory and dataloaders to be able to read in either a single file, a single folder, or a list of files from the config. It is up to the creator of any new dataloaders to implement the method of reading multiple files within import_data(). 
This has the added benefit of simplifying the dataloaders, as the init method can be abstracted for all dataloaders now; all dataloaders will go through the following initialisation process:
1. Read in config params
2. Add in default params per dataloader if required
3. Import data from files
4. Downsample if required
5. Reproject if required
6. Trim data to initial boundary
7. Set data variable name
'AMSR_folder' is now removed from the dataloaders,  replaced with the regular AMSR dataloader. This is the only change made to the regression …
> Enabling dataloaders to read from folder

- polar_route/dataloaders/factory.py
- polar_route/dataloaders/scalar/abstract_scalar.py
- polar_route/dataloaders/vector/abstract_vector.py
Fixed bug where downsampling was being performed when factors were (1,1), rather than being skipped over.
The dataloader factory set the default to be a tuple (1,1), and the abstract dataloaders made a check to see if downsample_factors was (1,1). This conflicted with downsample factors read in from JSON's, as tuple's are saved as lists in JSON format. This meant that the comparison being made was actually `if (1,1) == [1,1]`, which it doesn't, and hence the downsampling was being triggered.
To fix this, I amended the default value in the factory to be [1,1], and also changed the abstract dataloaders to be able to compare both tuples and lists. 
[Here](https://github.com/antarctica/PolarRoute/files/11203213/ds_fix_tests.txt) are the passed regression tests
> Downsampling factors as list vs tuple

- polar_route/cli.py
- polar_route/mesh_generation/environment_mesh.py
- setup.py
Adding ability to export EnvironmentMesh objects in standard geo.json format. 
Added optional argument 'format' to EnvironmentMesh.save(...)
Added CLI entry point 'export_mesh' 
All regression tests pass:
[pytest_DUMP.txt](https://github.com/antarctica/PolarRoute/files/11210318/pytest_DUMP.txt)
> Geo json output

- polar_route/__init__.py
- polar_route/cli.py
- polar_route/mesh_generation/environment_mesh.py
- polar_route/route_planner.py
Date: 2023-05-22
Version Number: 0.2.4  
Added `indent=4` to `json.dump()` to format the json outputs to be more easily readable by default.
Doesn't change any thing except json output files, so nothing would test it. Regardless, [here's](https://github.com/antarctica/PolarRoute/files/11531391/pytest_vessel.txt) the vessel tests passing to prove that nothing broke (vessel because it was the fastest).
> *include pytest.txt file showing all tests passing.*  
> *include pytest.txt file showing which tests fail.*  
> *include reasoning as to why your changes cause these tests to fail.* 
>
> Should these changes be valid, relevant test files should be updated.  
> *include pytest.txt file of test passing after test files have been updated.*
> Formatting json output

- docs/source/conf.py
- docs/source/index.rst
- docs/source/sections/Configuration.rst
- polar_route/__init__.py
- polar_route/cli.py
- polar_route/dataloaders/scalar/scalar_csv.py
- polar_route/dataloaders/vector/vector_csv.py
- polar_route/mesh_generation/environment_mesh.py
- polar_route/route_planner.py
- polar_route/vessel_performance/vessels/SDA.py
Date: 2023-05-23
Version Number: 0.2.6
Fixed a bug introduced in  #187 which prevented the cli from running `optimise_routes`. 
Also adjusted the cli to output the dijkstra path (if the -d flag is provided) **_before_** attempting to smooth the path. This enables us to get a path out even if the smoothing crashes. 
I should have caught the typo before pushing #187, so for now completeness, here's the [dijkstra](https://github.com/antarctica/PolarRoute/files/11542303/pytest_dijkstra.txt) and [smoothed](https://github.com/antarctica/PolarRoute/files/11542410/pytest_smoothed.txt) regression tests passing
> *include pytest.txt file showing all tests passing.*  
> *include pytest.txt file showing which tests fail.*  
> *include reasoning as to why your changes cause these tests to fail.* 
>
> …
> Fix typo and update CLI output order

- docs/source/sections/Dataloaders/AddingDataloaders.rst
- docs/source/sections/Dataloaders/Factory.rst
- docs/source/sections/Dataloaders/overview.rst
- docs/source/sections/Dataloaders/scalar/index.rst
- docs/source/sections/Dataloaders/vector/index.rst
- docs/source/sections/Discrete_meshing.rst
- polar_route/__init__.py
- polar_route/dataloaders/factory.py
- polar_route/dataloaders/scalar/abstract_scalar.py
- polar_route/dataloaders/scalar/amsr.py
- polar_route/dataloaders/scalar/scalar_grf.py
- polar_route/dataloaders/scalar/shape.py
- polar_route/dataloaders/vector/abstract_vector.py
- polar_route/dataloaders/vector/vector_grf.py
- polar_route/mesh_generation/mesh_builder.py
Date: 2023-05-25
Version Number: 0.2.7
Added ability to add dataloader to a pre-existing MeshBuilder object. This is designed primarily for external developers who do not wish to edit the repo just to add a new data source. 
Modified: polar_route/mesh_generation/mesh_builder.py
[pytest_mesh.txt](https://github.com/antarctica/PolarRoute/files/11566353/pytest_mesh.txt)
--------
There's a very minor, odd formatting case that I can't find a straight answer for, hence why PEP-8 is not checkmarked here. Line 208 of mesh_builder.py:
'Dataloader' is a class that is passed as an argument, and then gets initialised later in line 230. Sonar complains about the current formatting, but if it was changed to 'dataloader', then line 230 would look like a call to a method instead of initialising a class. …
> Implemented add_dataloader() 

- polar_route/__init__.py
- polar_route/dataloaders/vector/abstract_vector.py
Date: 2023-06-22
Version Number: 0.2.11
@gecoombs  found a bug when writing a new dataloader. This bug crashed the abstract_vector dataloader when it was trying to calculate the magnitude and direction of vectors, if there was a time dimension and the data was loaded as an xarray dataset. This has been fixed so that it should be flexible to any number of dimensions.
- [*] My changes have not altered any of the files listed in the testing strategy
- [*] My changes result in all required regression tests passing without the need to update test files.  
> `abstract_vector.py` was changed, but is not listed in testing strategy. I ran test_mesh.py as it seems to be the most relevant.
> [pytest_output.txt](https://github.com/antarctica/PolarRoute/files/11834822/pytest_output.txt)
- [*] My code …
> Fixed mag/dir calculation for  when time is a dimension

- docs/source/sections/Installation.rst
- polar_route/__init__.py
- polar_route/mesh_generation/environment_mesh.py
- requirements.txt
Date: 2023-07-06
Version Number: 0.2.12
Removed need for GDAL by default, instead only requiring it if the user wants to generate TIF's. This enables anyone to use the code without having to go through the headache that is GDAL
Issue raised in offline discussions
This has been tested both on my local computer (with GDAL installed), and on the BAS workstations (without GDAL installed). My computer produces TIFF images, whereas the workstations crash when trying to `export_mesh -f TIF`. This is expected behaviour for me, but I suppose we could handle the crash more elegantly? Thoughts?
> *Changed environment_mesh.py*
> [Passed tests](https://github.com/antarctica/PolarRoute/files/11950345/pytest_mesh.txt)
> GDAL as an optional requirement for 0.2.x

- polar_route/__init__.py
- polar_route/cli.py
- polar_route/mesh_generation/environment_mesh.py
Date: 13/07/23 
Version Number: 0.2.14 -> 0.2.15
Change the function that exports a mesh to geojson to average list values and remove infs and replace then with null values.
https://github.com/antarctica/SDADT-project/issues/147
Test dump:
[pytest_dump.txt](https://github.com/antarctica/PolarRoute/files/12039616/pytest_dump.txt)
Changed:
`polar_route/mesh_generation/environment_mesh.py`
> Reformat geojson output to remove infs

- polar_route/__init__.py
- polar_route/crossing.py
Date: 18/07/23
Version Number: 0.2.15 -> 0.2.16
This PR fixes an issue where if the Dijsktra route construction reached a point where it could not converge it simply exited with an exception. It now sets the cost of visiting that point to infinity and tries alternative paths.
Files changed:
`polar_route/crossing.py`
Test dump:
[pytest_dump.txt](https://github.com/antarctica/PolarRoute/files/12082953/pytest_dump.txt)
> Dijkstra convergence error

- docs/source/sections/Dataloaders/scalar/implemented/ERA5WaveHeight.rst
- docs/source/sections/Dataloaders/vector/implemented/ERA5WaveDirection.rst
- polar_route/dataloaders/factory.py
- polar_route/dataloaders/scalar/bsose_depth.py
- polar_route/dataloaders/scalar/bsose_sea_ice.py
- polar_route/dataloaders/scalar/era5_wave_height.py
- polar_route/dataloaders/vector/era5_wave_direction.py
Date: 25/07/23 
Version Number: 0.3.0
Adds dataloaders for significant wave height and mean wave direction (as a unit vector) from ERA5 reanalysis data.
Files changed:
```
docs/source/sections/Dataloaders/scalar/implemented/ERA5WaveHeight.rst
docs/source/sections/Dataloaders/vector/implemented/ERA5WaveDirection.rst
polar_route/dataloaders/factory.py
polar_route/dataloaders/scalar/bsose_depth.py
polar_route/dataloaders/scalar/bsose_sea_ice.py
polar_route/dataloaders/scalar/era5_wave_height.py
polar_route/dataloaders/vector/era5_wave_direction.py
polar_route/dataloaders/vector/era5_wind.py
```
> Wave dataloaders

- docs/source/sections/Configuration/Vessel_performance_config.rst
- polar_route/__init__.py
- polar_route/vessel_performance/vessels/abstract_glider.py
- polar_route/vessel_performance/vessels/abstract_ship.py
Date:  03/10/23
Version Number: 0.3.4 -> 0.3.5
Modify vessel performance code to allow arbitrarily named exclusion zones to be entered into the config and cells marked with those labels to be excluded from the neighbour graph.
Files changed:
```
docs/source/sections/Configuration/Vessel_performance_config.rst
polar_route/__init__.py
polar_route/vessel_performance/vessels/abstract_glider.py
polar_route/vessel_performance/vessels/abstract_ship.py
```
Test dump:
[vessel_test_dump.txt](https://github.com/antarctica/PolarRoute/files/12793000/vessel_test_dump.txt)
> Exclusion zone vessel performance

- polar_route/__init__.py
- polar_route/route_planner.py
Date: 05/10/23
Version Number: 0.3.6
Add in single value properties for the total fuel and travel time to the geojson route output for easy display in GIS software.
Files changed:
```
polar_route/__init__.py
polar_route/route_planner.py
```
Test dump: 
[route_test_dump.txt](https://github.com/antarctica/PolarRoute/files/12817045/route_test_dump.txt)
> Add in total traveltime and fuel properties to route output

- polar_route/__init__.py
- polar_route/cli.py
- polar_route/utils.py
Date: 2024-08-14
Version Number: 0.5.2   
Moves the extraction of routes into geojson format from `cli.py` to `utils.py` in order to make it accessible from a python interface rather that just through the CLI. Feature requested by @davidwilby 
To ensure that the functionality of the PolarRoute codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 
Passing reg tests: [reg_test.txt](https://github.com/user-attachments/files/16612196/reg_test.txt)
> Extract routes python interface hotfix

- polar_route/__init__.py
- polar_route/route_planner/route.py
- polar_route/route_planner/route_planner.py
- polar_route/route_planner/routing_info.py
- polar_route/route_planner/source_waypoint.py
Date: 02/09/24 
Version Number: 0.6.3
After playing around with one of the simple test examples and looking again at the `waypoint_correction` method of the `Route` class I found the source of the fuel bug that's been causing tests to fail. Turned out be an annoyingly simple indexing issue: the actual case value was being used to get the fuel values for this method instead of the corresponding index. All tests now pass, see the attached log.
I have now also added a change that fixes the bug identified in #291.
Further changes were made to ensure all relevant elements of the dijkstra graph match between v0.6 and v0.5.
The regression tests
Test dump: 
[route_tests_050924.txt](https://github.com/user-attachments/files/16887454/route_tests_050924.txt)
Files changed:
``` …
```
> Fix Indexing Bug for Fuel Values

- polar_route/__init__.py
- polar_route/route_planner/route_planner.py
Date: 17/10/24
Version Number: 1.1.0   
Remove assert statement to allow the route planner to run when some waypoints are outside the provided mesh. I also tidied up a few other waypoint related things for style etc.
Test results: [route_tests_171024.txt](https://github.com/user-attachments/files/17410967/route_tests_171024.txt)
Files changed:
```
polar_route/__init__.py
polar_route/route_planner/route_planner.py
```
> Ignore waypoints outside mesh instead of raising error

- polar_route/__init__.py
- polar_route/vessel_performance/vessel_performance_modeller.py
- polar_route/vessel_performance/vessels/abstract_alr.py
- polar_route/vessel_performance/vessels/abstract_glider.py
- polar_route/vessel_performance/vessels/abstract_plane.py
- polar_route/vessel_performance/vessels/abstract_ship.py
- polar_route/vessel_performance/vessels/abstract_uav.py
- polar_route/vessel_performance/vessels/example_ship.py
Date: 18/10/24  
Version Number: 1.1.1
Adds the option to specify a custom vessel class when initialising the vessel performance modeller (bypassing the vessel factory) to make prototyping new models simpler. Also fixes a couple of small bugs with existing vessel models (alr/plane).
Test results: [vessel_tests_181024.txt](https://github.com/user-attachments/files/17436753/vessel_tests_181024.txt)
Files changed:
```
polar_route/__init__.py
polar_route/vessel_performance/vessel_performance_modeller.py
polar_route/vessel_performance/vessels/abstract_alr.py
polar_route/vessel_performance/vessels/abstract_glider.py
polar_route/vessel_performance/vessels/abstract_plane.py
polar_route/vessel_performance/vessels/abstract_ship.py
polar_route/vessel_performance/vessels/abstract_uav.py …
```
> Add option for custom vessel performance classes

- polar_route/__init__.py
- polar_route/route_planner/crossing_smoothing.py
- polar_route/route_planner/route_planner.py
- polar_route/route_planner/source_waypoint.py
Date:    
Version Number:    
Fixing bug raised in #303 
Fixed bug where dijkstra was called multiple times for the same graph
Fixed bug where early stopping criterion was not present in the codebase
To ensure that the functionality of the PolarRoute codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 
> *list which files have been altered and include a pytest.txt file for each of
> the tests required to be run*
>
> The files which have been changed during this PR can …
> Bug Fixing - Path Smoothing failures

- polar_route/__init__.py
- polar_route/exceptions.py
- polar_route/route_calc.py
- polar_route/route_planner/crossing_smoothing.py
- polar_route/route_planner/route_planner.py
Date: 21/01/2025
Version Number: 1.1.3 -> 11.4
Adding custom exception classes for easier failure detection in the pipeline. 
[](https://github.com/antarctica/PolarRoute/issues/311)
To ensure that the functionality of the PolarRoute codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 
> *list which files have been altered and include a pytest.txt file for each of
> the tests required to be run*
>
> The files which have been changed during this PR can be listed using …
> Custom exceptions
